web:
    image: nginx:latest
    #you can find the website on localhost:3000
    ports:
        - "3000:8080"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code
